const claimLabels={screen:'Tela',event:'Evento',flow:'Fluxo',business_rule:'Regra de negócio',domain_entity:'Entidade',ux_pattern:'Padrão de experiência',glossary:'Conceito',gap:'Lacuna do projeto'};
const classificationLabels={observed:'Observada',narrated:'Narrada',inferred:'Inferida',unknown:'Desconhecida'};
const reviewLabels={pending:'Pendente',approved:'Aprovado',rejected:'Rejeitado',confirm:'Precisa confirmar'};
function knowledgeView(r,stages){return `<div class="notice">A análise com Gemini aguarda aprovação do prompt. As conclusões abaixo são registros de revisão manual.</div><div class="actions" style-placeholder="none"><h2>Conhecimento revisável</h2></div><div class="actions">${r.status==='review'?'<button class="primary" id="new-claim">＋ Registrar conclusão</button><button id="approve-knowledge">Fechar revisão e aprovar versão</button>':''}${r.status==='approved'?'<button class="primary" id="export-package">Gerar pacote para o Codex</button>':''}<button id="target-inventory">Inventariar projeto-alvo</button><button id="target-view">Ver inventário</button></div><div id="exports" class="list"></div><div id="target-output"></div><div class="grid">${r.claims.map(c=>`<article class="card"><div class="row"><span class="pill ${c.classification}">${classificationLabels[c.classification]}</span><span class="badge">${reviewLabels[c.review_status]}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><p class="muted">${claimLabels[c.type]} · Confiança ${Math.round(c.confidence*100)}% · ${c.evidence.length} evidência(s)</p><div class="actions">${r.status==='review'?`<button data-edit-claim="${c.id}">Editar / revisar</button>`:''}<button data-evidence-claim="${c.id}">Ver evidência ↗</button></div></article>`).join('')||'<div class="empty"><h3>Nenhuma conclusão registrada.</h3><p class="muted">Revise as telas e falas antes de descrever o comportamento do sistema.</p></div>'}</div><h2>Telas detectadas</h2><div class="grid">${(stages.screens?.result?.screens||[]).map(s=>`<article class="card"><span class="pill observed">Captura visual · pendente de revisão</span><h3>${esc(s.name)}</h3><p class="muted">${esc(s.note)}</p><div class="actions"><button data-screen-time="${s.timestamp}">Ver em ${timeLabel(s.timestamp)}</button>${r.status==='review'?`<button data-promote-screen="${s.id}">Revisar como tela</button><button data-redact="${s.frame_id}">Ocultar região</button>`:''}</div></article>`).join('')}</div>`;}
async function bindKnowledge(r,stages){
root.querySelectorAll('[data-screen-time]').forEach(b=>b.onclick=async()=>{await runView(r.id,'review');document.querySelector('#player').currentTime=Number(b.dataset.screenTime);});
root.querySelectorAll('[data-evidence-claim]').forEach(b=>b.onclick=async()=>{const c=r.claims.find(c=>c.id===b.dataset.evidenceClaim);await runView(r.id,'review');document.querySelector('#player').currentTime=Number(c.evidence[0].timestamp);});
root.querySelectorAll('[data-edit-claim]').forEach(b=>b.onclick=()=>claimForm(r,stages,r.claims.find(c=>c.id===b.dataset.editClaim)));
root.querySelectorAll('[data-promote-screen]').forEach(b=>b.onclick=()=>{const s=stages.screens.result.screens.find(s=>s.id===b.dataset.promoteScreen);claimForm(r,stages,{type:'screen',title:s.name,description:'Descreva a finalidade e os componentes visíveis.',classification:'observed',confidence:.8,evidence:[{id:s.frame_id}]});});
root.querySelectorAll('[data-redact]').forEach(b=>b.onclick=()=>redactionForm(r,stages.frames.result.frames.find(f=>f.id===b.dataset.redact)));
document.querySelector('#new-claim')?.addEventListener('click',()=>claimForm(r,stages));
document.querySelector('#approve-knowledge')?.addEventListener('click',async()=>{try{await api('/runs/'+r.id+'/approve','POST',{});toast('Versão aprovada e congelada.');await runView(r.id,'knowledge');}catch(e){toast(e.message);}});
document.querySelector('#export-package')?.addEventListener('click',async()=>{try{await api('/runs/'+r.id+'/exports','POST',{});toast('Gerando o pacote.');await refreshExports(r.id);}catch(e){toast(e.message);}});
document.querySelector('#target-inventory').onclick=async()=>{try{await api('/projects/'+r.project_id+'/target','POST',{});toast('Inventário da pasta autorizada enviado à fila.');}catch(e){toast(e.message);}};
document.querySelector('#target-view').onclick=async()=>{try{const result=await api('/projects/'+r.project_id+'/target');const area=document.querySelector('#target-output');if(!result||result.status!=='completed'){area.textContent=result?.error||'Inventário ainda não disponível. Aguarde o worker e tente novamente.';return;}const data=JSON.parse(result.result);area.innerHTML=`<div class="card list"><h2>Projeto-alvo · somente leitura</h2><p class="muted">${data.files.length} arquivo(s). Registre correspondências e lacunas como conclusões revisáveis. O inventário textual não comprova equivalência funcional.</p>${data.truncated?'<p class="notice">Inventário atingiu o limite configurado.</p>':''}${data.files.map(f=>`<div class="list-item"><strong>${esc(f.path)}</strong><p class="muted">${f.symbols.map(s=>esc(s.name)+' (linha '+s.line+')').join(' · ')||'Sem símbolos identificados.'}</p></div>`).join('')}</div>`;}catch(e){toast(e.message);}};
await refreshExports(r.id);
}
async function refreshExports(rid){const area=document.querySelector('#exports');if(!area)return;const items=await api('/runs/'+rid+'/exports');area.innerHTML=items.map(a=>`<div class="card row"><span>Pacote ${date(a.created_at)}</span>${a.status==='completed'?`<a href="/api/exports/${a.id}" download>Baixar ZIP ↓</a>`:`<span class="muted">${esc(a.error||stateLabels[a.status]||a.status)}</span>`}</div>`).join('');if(items.some(a=>a.status==='queued')){clearInterval(timer);timer=setInterval(()=>refreshExports(rid).catch(e=>toast(e.message)),3000);}else clearInterval(timer);}
function claimForm(r,stages,c={}){const frames=(stages.frames?.result?.frames||[]).filter(f=>f.included);const segments=stages.transcript?.result?.segments||[];const selected=new Set((c.evidence||[]).map(e=>e.id));const options=[...frames.map(f=>({id:f.id,label:'Frame · '+timeLabel(f.timestamp)})),...segments.map(s=>({id:s.id,label:'Fala · '+timeLabel(s.start)+' · '+s.text.slice(0,55)}))];
const dialog=document.createElement('dialog');dialog.innerHTML=`<form class="form"><h2>${c.id?'Revisar conclusão':'Registrar conclusão'}</h2><label>Tipo<select name="type">${Object.entries(claimLabels).map(([key,label])=>`<option value="${key}" ${key===(c.type||'business_rule')?'selected':''}>${label}</option>`).join('')}</select></label><label>Título<input name="title" required maxlength="200" value="${esc(c.title)}"></label><label>Descrição<textarea name="description" required maxlength="8000">${esc(c.description)}</textarea></label><div class="grid"><label>Classificação<select name="classification">${Object.entries(classificationLabels).map(([key,label])=>`<option value="${key}" ${key===(c.classification||'inferred')?'selected':''}>${label}</option>`).join('')}</select></label><label>Confiança (0 a 1)<input name="confidence" type="number" min="0" max="1" step="0.01" required value="${c.confidence??.5}"></label></div><label>Evidências (Ctrl para selecionar várias)<select name="evidence" multiple required size="5">${options.map(e=>`<option value="${e.id}" ${selected.has(e.id)?'selected':''}>${esc(e.label)}</option>`).join('')}</select></label>${c.id?`<label>Decisão da revisão<select name="review_status">${Object.entries(reviewLabels).map(([key,label])=>`<option value="${key}" ${key===c.review_status?'selected':''}>${label}</option>`).join('')}</select></label>`:'<p class="muted">Novas conclusões começam pendentes. Revise antes de aprovar.</p>'}<div class="actions"><button class="primary">Salvar</button><button type="button" class="close">Cancelar</button></div></form>`;root.append(dialog);dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.evidence=[...e.target.evidence.selectedOptions].map(o=>o.value);data.confidence=Number(data.confidence);try{await api('/runs/'+r.id+'/claims'+(c.id?'/'+c.id:''),c.id?'PATCH':'POST',data);dialog.close();await runView(r.id,'knowledge');}catch(err){toast(err.message);}};dialog.showModal();}
function redactionForm(r,f){const dialog=document.createElement('dialog');dialog.innerHTML=`<form class="form"><h2>Ocultar região sensível</h2><p class="muted">Frame ${f.width} × ${f.height} pixels. A região será pintada de preto no derivado. O OCR será recalculado e conclusões voltarão para revisão.</p><img src="/api/runs/${r.id}/frames/${f.id}" alt="Frame a proteger" width="480"><div class="grid"><label>X<input name="x" type="number" value="0" min="0" max="${f.width-1}" required></label><label>Y<input name="y" type="number" value="0" min="0" max="${f.height-1}" required></label><label>Largura<input name="width" type="number" value="${f.width}" min="1" max="${f.width}" required></label><label>Altura<input name="height" type="number" value="${f.height}" min="1" max="${f.height}" required></label></div><div class="actions"><button class="primary">Aplicar ocultação</button><button type="button" class="close">Cancelar</button></div></form>`;root.append(dialog);dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const k of ['x','y','width','height'])data[k]=Number(data[k]);try{await api('/runs/'+r.id+'/redact','POST',{...data,frame_id:f.id});dialog.close();await runView(r.id);}catch(err){toast(err.message);}};dialog.showModal();}
