const timeLabel=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const stateLabels={uploading:'Upload incompleto',validating:'Validando arquivo',ready:'Pronto para analisar',invalid:'Arquivo inválido',queued:'Na fila',processing:'Processando',review:'Aguardando revisão',completed:'Concluído',failed:'Falhou',cancelled:'Cancelado',pending:'Pendente',approved:'Aprovado'};
const stageLabels={audio:'Extração de áudio',transcript:'Transcrição local',frames:'Captura e deduplicação',ocr:'Reconhecimento de texto',screens:'Agrupamento de telas'};
let activeRun=null;
window.renderMediaProject=async p=>{
clearInterval(timer);const videos=await api('/projects/'+p.id+'/videos');
shell(`<div class="row"><div><span class="eyebrow">PROJETO · ${esc(p.domain||'GERAL')}</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.objective)}</p></div><div class="actions"><button id="edit">Editar</button><button class="primary" id="upload">＋ Enviar vídeo</button></div></div><p class="muted">Pasta de saída: <code>${p.output_directory?`outputs/${esc(p.output_directory)}/`:'Preparando pasta do projeto…'}</code></p><div class="tabs"><button class="active">Vídeos e análises</button><button id="archive">${p.status==='active'?'Arquivar projeto':'Restaurar projeto'}</button></div><div class="grid">${videos.map(v=>{const metadata=v.metadata?JSON.parse(v.metadata):{};const runs=v.runs?JSON.parse(v.runs):[];return `<article class="card"><div class="row"><span class="card-icon">▷</span><span class="badge">${stateLabels[v.status]||esc(v.status)}</span></div><h3>${esc(v.title)}</h3><p class="muted">${esc(v.original_name)} · ${(v.size/1048576).toFixed(1)} MB</p>${metadata.duration?`<p class="muted">${timeLabel(metadata.duration)} · ${metadata.width} × ${metadata.height} · ${esc(metadata.video_codec)}</p>`:''}${metadata.duplicate_of?'<p class="notice">Arquivo idêntico a outro vídeo deste projeto.</p>':''}${v.error?`<p class="error">${esc(v.error)}</p>`:''}<div class="bottom actions">${v.status==='ready'?`<button class="primary" data-analyze="${v.id}">Nova análise</button>`:''}${v.status==='uploading'?`<button data-resume-upload="${v.id}">Retomar upload</button>`:''}${runs.map(r=>`<div class="output-run-buttons"><button data-run="${r.id}">v${r.version} · ${stateLabels[r.status]||esc(r.status)} ↗</button><button data-open-outputs="${r.id}">Frames e textos · v${r.version}</button></div>`).join('')}</div></article>`;}).join('')||'<div class="empty"><div class="big">▷</div><h2>Comece pela referência.</h2><p class="muted">Envie uma demonstração em MP4, MOV, MKV ou WebM.<br>Os arquivos permanecem no ambiente local.</p></div>'}</div>`);
document.querySelector('#edit').onclick=()=>projectForm(p);document.querySelector('#upload').onclick=()=>uploadForm(p);document.querySelector('#archive').onclick=async()=>{await api('/projects/'+p.id,'PATCH',{...p,status:p.status==='active'?'archived':'active'});current=null;navigate('projects');};
root.querySelectorAll('[data-analyze]').forEach(b=>b.onclick=()=>analysisForm(videos.find(v=>v.id===b.dataset.analyze)));
root.querySelectorAll('[data-open-outputs]').forEach(b=>b.onclick=()=>runView(b.dataset.openOutputs,'outputs'));
root.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>runView(b.dataset.run));root.querySelectorAll('[data-resume-upload]').forEach(b=>b.onclick=()=>uploadForm(p,videos.find(v=>v.id===b.dataset.resumeUpload)));
if(videos.some(v=>v.status==='validating'))timer=setInterval(()=>window.renderMediaProject(p).catch(e=>toast(e.message)),4000);
};
function uploadForm(p,resume){clearInterval(timer);shell(`<span class="eyebrow">REFERÊNCIAS</span><h1>${resume?'Retomar envio':'Enviar uma demonstração'}</h1><p class="muted">Upload em blocos. Se a conexão cair, selecione o mesmo arquivo para continuar.</p><form id="upload-form" class="card form"><label>Vídeo<input class="file-input" type="file" name="video" accept=".mp4,.mov,.mkv,.webm" required></label><label>Título<input name="title" required maxlength="200" value="${esc(resume?.title)}"></label><label>Origem<input name="origin" placeholder="Ex.: demonstração autorizada pela equipe" value="${esc(resume?.origin)}"></label><label>Contexto<textarea name="context">${esc(resume?.context)}</textarea></label><label>Sensibilidade<select name="sensitivity"><option value="internal">Interno</option><option value="sensitive">Sensível</option><option value="public">Público</option></select></label><p class="muted">O vídeo é tratado como dado e nunca executado. Análises externas estão desativadas.</p><progress id="upload-progress" class="progress" max="100" value="0" aria-label="Progresso do upload"></progress><span id="upload-status" role="status"></span><div class="actions"><button class="primary" id="send">Enviar vídeo</button><button type="button" id="cancel-upload">Voltar</button></div></form>`);document.querySelector('#cancel-upload').onclick=()=>openProject(p.id);
document.querySelector('#upload-form').onsubmit=async e=>{e.preventDefault();const form=e.target, file=form.video.files[0],button=document.querySelector('#send');button.disabled=true;try{let vid=resume?.id;if(resume&&(file.name!==resume.original_name||file.size!==Number(resume.size)))throw Error('Selecione o mesmo arquivo do upload original.');if(!vid){const data=Object.fromEntries(new FormData(form));delete data.video;const d=await api('/projects/'+p.id+'/videos','POST',{...data,name:file.name,size:file.size});vid=d.id;resume={id:vid,original_name:file.name,size:file.size};}
const uploaded=await api('/uploads/'+vid);const existing=new Map(uploaded.chunks.map(c=>[Number(c.number),c.sha256]));const count=Math.ceil(file.size/8388608);
for(let i=0;i<count;i++){const chunk=file.slice(i*8388608,Math.min(file.size,(i+1)*8388608));if(existing.has(i)){const digest=await crypto.subtle.digest('SHA-256',await chunk.arrayBuffer());const hash=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');if(hash!==existing.get(i))throw Error('O arquivo selecionado difere dos blocos já enviados.');}else{const response=await fetch(`/api/uploads/${vid}/chunks/${i}`,{method:'PUT',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/octet-stream'},body:chunk});if(!response.ok)throw Error((await response.json()).error);}
document.querySelector('#upload-progress').value=(i+1)/count*100;document.querySelector('#upload-status').textContent=`Bloco ${i+1} de ${count}`;}
await api('/uploads/'+vid+'/complete','POST',{});toast('Upload concluído. Validando o arquivo no worker.');await openProject(p.id);
}catch(err){toast(err.message);button.disabled=false;}};
}
function analysisForm(v){shell(`<span class="eyebrow">PROCESSAMENTO</span><h1>Configure a análise</h1><p class="muted">${esc(v.title)}</p><form class="form card" id="analysis-form"><label>Perfil<select name="profile"><option value="quick">Rápido · captura a cada 15 segundos</option><option value="balanced" selected>Equilibrado · captura a cada 5 segundos</option><option value="detailed">Detalhado · captura a cada 2 segundos</option></select></label><label>Intervalo de captura (segundos)<input name="interval" type="number" min="1" max="120" value="5"></label><label>Sensibilidade de cena<input name="scene" type="number" min="0.05" max="0.95" step="0.05" value="0.30"></label><div class="notice">Mídia, OCR e transcrição usam motores locais. A análise semântica Astra ainda não está ativada.</div><div class="actions"><button class="primary">Iniciar processamento →</button><button type="button" id="back-project">Voltar</button></div></form>`);document.querySelector('#back-project').onclick=()=>openProject(v.project_id);const form=document.querySelector('#analysis-form');form.profile.onchange=()=>{const preset={quick:[15,.5],balanced:[5,.3],detailed:[2,.15]}[form.profile.value];form.interval.value=preset[0];form.scene.value=preset[1];};form.onsubmit=async e=>{e.preventDefault();try{const r=await api('/videos/'+v.id+'/runs','POST',Object.fromEntries(new FormData(form)));await runView(r.id);}catch(err){toast(err.message);}};}
async function runView(rid,section='monitor'){
clearInterval(timer);const r=await api('/runs/'+rid);activeRun=r;const stages=Object.fromEntries(r.stages.map(s=>[s.name,s]));const done=r.stages.filter(s=>s.status==='completed').length;
let content='';
if(section==='monitor')content=`<div class="card"><div class="row"><h2>${stateLabels[r.status]||esc(r.status)}</h2><strong>${done} / 5 etapas</strong></div><progress class="progress" max="5" value="${done}" aria-label="Etapas concluídas"></progress>${r.error?`<p class="error">${esc(r.error)}</p>`:''}<div class="list">${['audio','transcript','frames','ocr','screens'].map(s=>`<div class="list-item row"><div><strong>${stageLabels[s]}</strong>${stages[s]?.error?`<p class="error">${esc(stages[s].error)}</p>`:''}</div><span class="badge">${stateLabels[stages[s]?.status]||'Pendente'}</span>${['review','failed','cancelled'].includes(r.status)?`<button data-retry="${s}">Repetir a partir daqui</button>`:''}</div>`).join('')}</div><div class="actions">${['processing','queued'].includes(r.status)?'<button id="cancel-run" class="danger">Cancelar execução</button>':''}${['failed','cancelled'].includes(r.status)?'<button id="resume-run" class="primary">Retomar etapas pendentes</button>':''}</div></div>`;
if(section==='review'){const segments=stages.transcript?.result?.segments||[];const frames=stages.frames?.result?.frames||[];content=`<div class="review-grid"><div><video id="player" controls preload="metadata" src="/api/videos/${r.video_id}/stream"></video><p class="muted">Navegue por frames e falas para posicionar o vídeo no instante da evidência.</p><input type="search" id="search-evidence" placeholder="Pesquisar fala ou texto reconhecido" aria-label="Pesquisar evidências"><div class="frames" id="frames" aria-label="Frames capturados">${frames.filter(f=>f.included).map(f=>`<button data-time="${f.timestamp}" data-frame="${f.id}"><img loading="lazy" src="/api/runs/${rid}/frames/${f.id}" alt="Frame em ${timeLabel(f.timestamp)}"><span>${timeLabel(f.timestamp)}</span></button>`).join('')}</div></div><div class="card"><h2>Transcrição</h2><div class="scroll" id="transcript">${segments.map(s=>`<div class="list-item" data-segment="${s.id}"><button class="segment" data-time="${s.start}"><span class="pill">${timeLabel(s.start)}</span> ${esc(s.text)}</button>${r.status==='review'?`<button data-edit-segment="${s.id}">Editar fala</button>`:''}</div>`).join('')||`<p class="muted">${esc(stages.transcript?.result?.reason||'A transcrição ainda não está disponível.')}</p>`}</div><h2>Texto da tela</h2><div id="ocr-text" class="muted">Selecione um frame para consultar o OCR.</div></div></div>`;}
if(section==='knowledge')content=knowledgeView(r,stages);
if(section==='outputs')content=outputsView();
shell(`<div class="row"><div><span class="eyebrow">ANÁLISE · VERSÃO ${r.version}</span><h1>${esc(r.title)}</h1><p class="muted">${date(r.created_at)} · Perfil ${esc(r.config.profile)}</p></div><button id="back-project">Voltar ao projeto</button></div><div class="tabs">${[['monitor','Processamento'],['review','Revisão sincronizada'],['outputs','Frames e textos'],['knowledge','Conhecimento e exportação']].map(([id,label])=>`<button class="${section===id?'active':''}" data-section="${id}">${label}</button>`).join('')}</div>${content}`);
document.querySelector('#back-project').onclick=()=>openProject(r.project_id);root.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>runView(rid,b.dataset.section));
document.querySelector('#cancel-run')?.addEventListener('click',async()=>{await api('/runs/'+rid+'/cancel','POST',{});await runView(rid);});document.querySelector('#resume-run')?.addEventListener('click',async()=>{try{await api('/runs/'+rid+'/resume','POST',{});await runView(rid);}catch(e){toast(e.message);}});root.querySelectorAll('[data-retry]').forEach(b=>b.onclick=async()=>{try{await api('/runs/'+rid+'/resume','POST',{stage:b.dataset.retry});await runView(rid);}catch(e){toast(e.message);}});
root.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{document.querySelector('#player').currentTime=Number(b.dataset.time);if(b.dataset.frame){const blocks=stages.ocr?.result?.blocks||[];document.querySelector('#ocr-text').textContent=blocks.filter(c=>c.frame_id===b.dataset.frame).map(c=>c.text).join(' ')||'Nenhum texto reconhecido.';}});
root.querySelectorAll('[data-edit-segment]').forEach(b=>b.onclick=()=>{const s=stages.transcript.result.segments.find(s=>s.id===b.dataset.editSegment);editDialog('Editar transcrição',s.text,async text=>{await api(`/runs/${rid}/transcript/${s.id}`,'PATCH',{text});await runView(rid,'review');});});
document.querySelector('#search-evidence')?.addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase('pt-BR');root.querySelectorAll('[data-segment]').forEach(el=>el.hidden=!el.textContent.toLocaleLowerCase('pt-BR').includes(q));const blocks=stages.ocr?.result?.blocks||[];root.querySelectorAll('[data-frame]').forEach(el=>el.hidden=q&&!blocks.some(b=>b.frame_id===el.dataset.frame&&b.text.toLocaleLowerCase('pt-BR').includes(q)));});
if(section==='knowledge')bindKnowledge(r,stages);
if(section==='outputs')bindOutputs(r,stages);
if(section==='monitor'&&r.status==='failed'&&r.config.redaction_pending){const retry=document.createElement('button');retry.className='primary';retry.textContent='Retomar ocultação pendente';retry.onclick=async()=>{try{const pending=r.config.redaction_pending;await api('/runs/'+rid+'/redact','POST',{frame_id:pending.frame_id,...pending.box});await runView(rid);}catch(e){toast(e.message);}};document.querySelector('#main').append(retry);}
if(section==='monitor'&&['queued','processing'].includes(r.status))timer=setInterval(()=>runView(rid).catch(e=>toast(e.message)),3000);
}
function editDialog(title,value,save){const dialog=document.createElement('dialog');dialog.innerHTML=`<form class="form"><h2>${esc(title)}</h2><label>Texto<textarea name="text" required maxlength="8000">${esc(value)}</textarea></label><div class="actions"><button class="primary">Salvar revisão</button><button type="button" class="close">Cancelar</button></div></form>`;root.append(dialog);dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await save(e.target.text.value);dialog.close();}catch(err){toast(err.message);}};dialog.showModal();}
function knowledgeView(r,stages){return `<div class="notice">Astra está desativado. Telas foram agrupadas por imagem e OCR; regras e fluxos não foram inferidos automaticamente.</div><div class="grid">${(stages.screens?.result?.screens||[]).map(s=>`<article class="card"><span class="pill observed">Observada</span><h3>${esc(s.name)}</h3><p class="muted">${esc(s.note)}</p><button data-screen-time="${s.timestamp}">Ver evidência em ${timeLabel(s.timestamp)}</button></article>`).join('')}</div>`;}
function bindKnowledge(r){root.querySelectorAll('[data-screen-time]').forEach(b=>b.onclick=()=>runView(r.id,'review'));}
