services:
  web:
    volumes:
      - ./app:/app:ro
      - ./frontend:/frontend:ro
  gemini-worker:
    volumes:
      - ./app:/app:ro
  worker:
    volumes:
      - ./worker:/worker:ro
  scheduler:
    volumes:
      - ./worker:/worker:ro
  nginx:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
