const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context=vm.createContext({esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))});
vm.runInContext(fs.readFileSync('frontend/gemini.js','utf8'),context);
const settings={has_key:false,validated_at:null,models:[],model:'',prompt:'base',default_prompt:'base',draft_version:0};
const setup=context.geminiSettingsMarkup(settings);
assert.match(setup,/Chave API/);assert.match(setup,/gemini-model/);assert.match(setup,/Instruções avançadas/);
assert.doesNotMatch(setup,/gemini-analyze|gemini-report|Iniciar análise/);
const run={id:'a'.repeat(32),status:'review',outputs:{screens:true}};
const counts={segments:4,blocks:2,images:1};
function html(job,config=settings,r=run){return context.geminiAnalysisMarkup(r,config,job,counts);}
const idle=html({status:'not_started'});
assert.match(idle,/gemini-configure/);assert.doesNotMatch(idle,/gemini-analyze|gemini-report|name="api_key"|gemini-prompt/);
const configured={...settings,has_key:true,validated_at:'2026-09-27',model:'gemini-test'};
const ready=html({status:'not_started'},configured);
assert.match(ready,/Iniciar análise com Gemini/);assert.match(ready,/4 trechos/);
assert.doesNotMatch(ready,/Chave API|gemini-model|gemini-prompt|gemini-report/);
const waiting=html({status:'not_started'},configured,{...run,status:'processing',outputs:{screens:false}});
assert.match(waiting,/gemini-monitor/);assert.doesNotMatch(waiting,/gemini-analyze/);
const processing=html({status:'processing',progress_done:2,progress_total:5},configured);
assert.match(processing,/Partes analisadas: 2 de 5/);assert.match(processing,/gemini-cancel/);assert.doesNotMatch(processing,/gemini-analyze|gemini-report/);
const complete=html({status:'completed',model:'gemini-test',id:'b'.repeat(32),warnings:[]},configured);
assert.match(complete,/gemini-report/);assert.match(complete,/Baixar Markdown/);
assert.match(complete,/<details class="form-details ai-repeat">/);
assert.doesNotMatch(complete,/name="api_key"|gemini-model|gemini-prompt/);
const failed=html({status:'failed',error:'Falha <externa>'},configured);
assert.match(failed,/Análise falhou/);assert.match(failed,/Falha &lt;externa&gt;/);assert.match(failed,/gemini-analyze/);assert.match(failed,/gemini-configure/);
console.log('PASS: configuração separada; análise tem começo, progresso, falha e relatório como estado final; conteúdo escapado');
