const assert=require('node:assert/strict');
const vm=require('node:vm');
(async()=>{
 const sources=await Promise.all(['progress','library'].map(async name=>{const r=await fetch('http://localhost:8095/assets/'+name+'.js');assert.equal(r.status,200);return r.text();}));
 const context={esc:s=>String(s??'').replace(/"/g,'&quot;'),stageLabels:{audio:'Áudio',transcript:'Transcrição',frames:'Imagens',ocr:'OCR',screens:'Telas'},stateLabels:{}};
 vm.createContext(context);vm.runInContext(sources.join('\n'),context);
 vm.runInContext(`
 const stages=['audio','transcript','frames','ocr','screens'].map(name=>({name,status:'pending'}));
 const pending={id:'test',status:'queued',stages,outputs:{transcript:false,screens:false,files:false,ai:false}};
 globalThis.queued=progressView(pending);
 globalThis.locked=runOutputsHome(pending,{});
 globalThis.disabled=outputDisabled(pending,'transcript');
 globalThis.blockedSections=['transcript','screens','files','ai'].map(s=>outputEnabled(pending,s));
 stages[0].status='completed';stages[1].status='processing';pending.status='processing';
 globalThis.running=progressView(pending);
 stages.forEach(s=>s.status='completed');pending.status='review';
 globalThis.finalizing=progressView(pending);
 pending.outputs={transcript:true,screens:true,files:true,ai:false};
 globalThis.complete=progressView(pending);
 globalThis.unlocked=outputDisabled(pending,'transcript');
 globalThis.noPolling=runNeedsRefresh(pending);
 pending.status='failed';stages[1].status='failed';pending.outputs.transcript=false;
 globalThis.failed=progressView(pending);
 pending.status='cancelled';globalThis.cancelled=progressView(pending);
 `,context);
 assert.match(context.queued,/Na fila/);assert.match(context.queued,/value="0"/);
 assert.match(context.disabled,/disabled/);assert.deepEqual(Array.from(context.blockedSections),[false,false,false,true]);
 assert.equal((context.locked.match(/disabled aria-disabled/g)||[]).length,3);
 assert.match(context.running,/value="1"/);assert.match(context.running,/20% das etapas/);
 assert.match(context.finalizing,/Finalizando arquivos/);assert.match(context.complete,/Processamento concluído/);
 assert.equal(context.unlocked,'');assert.equal(context.noPolling,false);
 assert.match(context.failed,/interrompido/);assert.match(context.cancelled,/cancelado/);
 const buttons=['transcript','screens','ai'].map(section=>({dataset:{section},setAttribute(){}}));
 const live={innerHTML:''},connection={textContent:''};
 context.root={querySelectorAll:()=>buttons};
 context.host={isConnected:true,querySelector:id=>id==='#live-run-progress'?live:connection};
 context.setInterval=fn=>{context.tick=fn;return 1};context.clearInterval=()=>{};
 context.runView=async(...args)=>{context.routed=args};
 context.seed={id:'poll',status:'queued',stages:[{name:'transcript',status:'pending'}],outputs:{transcript:false,screens:false}};
 context.api=async()=>({id:'poll',status:'processing',stages:[{name:'transcript',status:'completed'}],outputs:{transcript:true,screens:false}});
 vm.runInContext("startRunRefresh(seed,'monitor',host)",context);
 await context.tick();
 assert.equal(context.routed[1],'monitor','polling must stay on the processing screen');
 assert.equal(buttons[0].disabled,false);assert.equal(buttons[1].disabled,true);assert.equal(buttons[2].disabled,false);
 context.host.isConnected=false;context.routed=null;
 await context.tick();assert.equal(context.routed,null,'detached screens must not navigate');
 context.host.isConnected=true;context.api=async()=>{throw Error('offline')};
 await context.tick();assert.match(connection.textContent,/reconectar/);
 console.log('PASS: progress rendering, output locks, stage-based percentages, finalization, completion, failure and cancellation');
 console.log('PASS: polling preserves monitor, releases completed output, ignores detached screens and reports connection failure');
})().catch(e=>{console.error(e);process.exitCode=1});
