from foundation import client,request
from media import eventually
from pathlib import Path
import json
import subprocess

saved=json.loads(Path('/tmp/ske-media-test.json').read_text());c=client();csrf=request(c,'/session')[1]['csrf'];csrf=request(c,'/login','POST',{'email':saved['email'],'password':saved['password']},csrf)[1]['csrf']
status,r=request(c,f"/videos/{saved['video_id']}/runs",'POST',{'profile':'quick'},csrf);assert status==202,r
rid=r['id'];r=eventually(lambda:request(c,'/runs/'+rid)[1],lambda x:x['status']in ['review','failed']);assert r['status']=='review'
frame=next(s['result']['frames'][0] for s in r['stages'] if s['name']=='frames')
pending={'frame_id':frame['id'],'box':{'x':0,'y':0,'width':20,'height':20}}
# Inject a crash checkpoint only into the run generated by this test.
code='import sys,json; from service import database; p=json.load(sys.stdin); db=database(); db.execute("UPDATE runs SET status=%s,config=config || %s::jsonb WHERE id=%s",("failed",json.dumps({"redaction_pending":p["pending"]}),p["rid"])); db.commit()'
subprocess.run(['docker','compose','exec','-T','worker','python','-c',code],input=json.dumps({'rid':rid,'pending':pending}).encode(),check=True)
assert request(c,f'/runs/{rid}/resume','POST',{},csrf)[0]==409
assert request(c,f'/runs/{rid}/redact','POST',{'frame_id':frame['id'],'x':1,'y':0,'width':20,'height':20},csrf)[0]==409
assert request(c,f'/runs/{rid}/redact','POST',{'frame_id':frame['id'],**pending['box']},csrf)[0]==202
done=eventually(lambda:request(c,'/runs/'+rid)[1],lambda x:x['status']in ['review','failed']);assert done['status']=='review',done
assert 'redaction_pending'not in done['config']
print('PASS: interrupted redaction cannot be bypassed or replaced and can resume safely')
