"""Public local registration and compatibility with the existing login flow."""
from foundation import client,request
import json
import subprocess
import uuid

suffix=uuid.uuid4().hex[:12]
created=[]
def csrf(c):return request(c,'/session')[1]['csrf']
def data(login,password='simples'):
    return {'email':login,'password':password,'password_confirmation':password}
try:
    c=client();token=csrf(c);name='Pessoa_'+suffix
    assert request(c,'/register','POST',data(name))[0]==419
    for invalid in ['ab','nome com espaço','<script>','nome@','a'*255]:
        assert request(c,'/register','POST',data(invalid),token)[0]==422
    for password in ['12345',' '*6,'a'*129]:
        assert request(c,'/register','POST',data(name,password),token)[0]==422
    assert request(c,'/register','POST',{**data(name),'password_confirmation':'diferente'},token)[0]==422
    assert request(c,'/register','POST',{**data(name),'password':[]},token)[0]==422
    status,session=request(c,'/register','POST',{**data(name),'role':'admin'},token)
    assert status==201,session
    created.append(name.lower())
    assert session['user']['email']==name.lower() and session['user']['role']=='user'
    assert session['csrf']!=token
    assert request(c,'/projects')[1]==[]
    assert request(c,'/session')[1]['user']['id']==session['user']['id']
    assert request(c,'/register','POST',data('outra_'+suffix),session['csrf'])[0]==409
    assert request(c,'/logout','POST',{},session['csrf'])[0]==200
    token=csrf(c)
    assert request(c,'/register','POST',data(name.upper()),token)[0]==409
    assert request(c,'/login','POST',{'email':name,'password':'errada'},token)[0]==401
    status,again=request(c,'/login','POST',{'email':'  '+name.upper()+'  ','password':'simples'},token)
    assert status==200 and again['user']['id']==session['user']['id']
    assert request(c,'/logout','POST',{},again['csrf'])[0]==200
    mail='cadastro-'+suffix+'@local.test';other=client()
    status,email_session=request(other,'/register','POST',data(mail,'abc123'),csrf(other))
    assert status==201,email_session
    created.append(mail)
    request(other,'/logout','POST',{},email_session['csrf'])
    # Inspect only the records generated by this test; plaintext must never be stored.
    verify="require 'src/bootstrap.php'; $names=json_decode(stream_get_contents(STDIN),true); foreach($names as $i=>$name){$u=query('SELECT password_hash,role FROM users WHERE email=?',[$name])->fetch(PDO::FETCH_ASSOC); if($u['role']!=='user'||!password_verify($i===0?'simples':'abc123',$u['password_hash'])||!str_starts_with($u['password_hash'],'$argon2id$'))exit(1);}"
    subprocess.run(['docker','compose','exec','-T','web','php','-r',verify],input=json.dumps(created).encode(),check=True)
    from pathlib import Path
    saved=json.loads(Path('/tmp/ske-media-test.json').read_text())
    old=client();assert request(old,'/login','POST',{'email':saved['email'],'password':saved['password']},csrf(old))[0]==200
    assert request(old,'/projects/'+saved['project_id'])[0]==200
    assert request(c,'/login','POST',{'email':name,'password':'simples'},csrf(c))[0]==200
    assert request(c,'/projects/'+saved['project_id'])[0]==404
    print('PASS: public registration, simple username/email, six-character password, confirmation, duplicate normalization, immediate session, non-admin role, hashed password, legacy login and project isolation')
finally:
    cleanup="require 'src/bootstrap.php'; $names=json_decode(stream_get_contents(STDIN),true); foreach($names as $name){$uid=query('SELECT id FROM users WHERE email=?',[$name])->fetchColumn();query('DELETE FROM audit_events WHERE actor_id=?',[$uid]);query('DELETE FROM users WHERE id=?',[$uid]);}"
    subprocess.run(['docker','compose','exec','-T','web','php','-r',cleanup],input=json.dumps(created).encode(),check=True)
